In [1]:
#Ques 1
import numpy as np

In [2]:
#Ques 2
arr = np.zeros(20)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Ques 3
arr = np.ones(20)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#Ques 4
arr=np.array([[1, ' ','none',10],['hi', 23,True,' '],[' ',4,False,3]],dtype='bool')
print(arr)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False  True]]


In [5]:
#Ques 5
arr = np.arange(100,200,dtype='float64')
print(arr)

[100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112. 113.
 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126. 127.
 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140. 141.
 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153. 154. 155.
 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167. 168. 169.
 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181. 182. 183.
 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195. 196. 197.
 198. 199.]


In [6]:
#Ques 6
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
#Ques 7
myarray = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
newarray = myarray[::-1]
print(newarray)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
#Ques 8
arr=np.array([12,34,0,4,0,2,3,0,123])
print(np.where(arr>0))

(array([0, 1, 3, 5, 6, 8], dtype=int64),)


In [9]:
#Ques 9
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
z=np.where(arr%2==0, -1, arr)
print(z)

[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1]


In [10]:
#Ques 10
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
z = np.where(arr % 2==1 , -1,arr)
print(z)

[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14]


In [11]:
#Ques 11
r = np.random.randint(100,300,size=(5,3))
print(r)
print(np.min(r), np.max(r))

[[192 200 171]
 [121 220 285]
 [235 275 200]
 [184 192 227]
 [136 232 217]]
121 285


In [12]:
#Ques 12
arr= np.random.random(30)
print(arr)
mean = arr.mean()
print (mean)

[0.73665121 0.25771976 0.78660233 0.02512459 0.90178493 0.11693557
 0.85852264 0.376195   0.97167247 0.6433985  0.85278986 0.50293561
 0.85356674 0.40217365 0.91816751 0.99960523 0.60804215 0.17373532
 0.72870392 0.89696564 0.10208323 0.11170264 0.87262231 0.373118
 0.68147522 0.75999775 0.7006787  0.06384992 0.69637829 0.12073912]
0.5697979267535073


In [13]:
#Ques 17
False

False

In [14]:
#Ques 18
Z = np.random.random((5,5))
Zmax, Zmin = np.max(Z), np.min(Z)
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.09875069 0.66618004 0.44023928 0.33650446 0.97432662]
 [0.70280501 0.46615807 0.49912187 0.26217684 0.27274916]
 [0.07741303 1.         0.         0.0466846  0.31804208]
 [0.94258552 0.69215893 0.75944591 0.37092518 0.27978001]
 [0.93676174 0.40870413 0.25979418 0.95412226 0.5038597 ]]


In [15]:
#Ques 19
a=np.ones((5,3))
b=np.ones((3,2))
arr=np.dot(a,b)
print(arr)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [17]:
#Ques 20
a= np.array([1, 4 ,8,35,6])
b= np.array([35,4])
print(np.intersect1d(a,b))

[ 4 35]


In [18]:
#Ques 21
y = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",y)
t = np.datetime64('today', 'D')
print("Today: ",t)
to = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",to)

Yestraday:  2020-05-27
Today:  2020-05-28
Tomorrow:  2020-05-29


In [19]:
#Ques 22
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [20]:
#Ques 23
Z = np.array([1.234,2.345,5.678,666.543,123.99])
n=Z.astype(int)
n

array([  1,   2,   5, 666, 123])

In [21]:
#Ques 24
arr = np.arange(2,22)
print(arr.reshape(4,5))

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]]


In [22]:
#Ques 25
ar1=np.arange(5)
ar2=np.arange(5,10)
print(np.vstack([ar1,ar2]))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
#Ques 26
ar1=np.arange(5)
ar2=np.arange(5,10)
print(np.hstack([ar1,ar2]))

[0 1 2 3 4 5 6 7 8 9]


In [26]:
#Ques 27
x = np.arange(1,10).reshape(3,3)
print(x)
y = np.arange(10,19).reshape(3,3)
print(y)
print("After stacking")
print(np.hstack((x,y[ : ,-2: ])))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
After stacking
[[ 1  2  3 11 12]
 [ 4  5  6 14 15]
 [ 7  8  9 17 18]]


In [27]:
#Ques 28
arr= np.arange(16).reshape(4,4)
print(arr)
arr[:,[1,3]] = arr[:,[3,1]]
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  3  2  1]
 [ 4  7  6  5]
 [ 8 11 10  9]
 [12 15 14 13]]


In [28]:
#Ques 29
sr = np.arange(16).reshape(4,4)
print(sr)
sr[[1,3]] = sr[[3,1]]
print(sr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]]
